FROM registry.access.redhat.com/ubi9/ubi-minimal:9.6

LABEL org.opencontainers.image.vendor="La Positiva Seguros" \
      pe.com.lapositiva.stack="Java-SpringBoot" \
      pe.com.lapositiva.runtime="ECS-Fargate" \
      pe.com.lapositiva.observability="base"

RUN microdnf install -y java-21-openjdk-headless tzdata shadow-utils curl-minimal && \
    microdnf clean all && \
    groupadd -r lapositiva && \
    useradd -r --no-log-init -g lapositiva -d /opt/lapositiva/app -s /sbin/nologin lapositiva && \
    mkdir -p /opt/lapositiva/app/tmp && \
    chown -R lapositiva:lapositiva /opt/lapositiva/app

WORKDIR /opt/lapositiva/app
COPY --chown=lapositiva:lapositiva app.jar ./app.jar

ENV TZ=America/Lima \
    SPRING_PROFILES_ACTIVE=default \
    JAVA_TOOL_OPTIONS="-XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError -Djava.io.tmpdir=/opt/lapositiva/app/tmp"

EXPOSE 8080
STOPSIGNAL SIGTERM
USER lapositiva
ENTRYPOINT ["java", "-jar", "app.jar"]
