FROM registry.access.redhat.com/ubi9/nodejs-24 AS build
WORKDIR /opt/app-root/src
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build && npm prune --omit=dev

FROM registry.access.redhat.com/ubi9/nodejs-24-minimal
LABEL org.opencontainers.image.vendor="La Positiva Seguros" \
      pe.com.lapositiva.stack="Node24-TypeScript-Fastify" \
      pe.com.lapositiva.runtime="ECS-Fargate" \
      pe.com.lapositiva.observability="base"
USER 0
RUN microdnf install -y curl-minimal && microdnf clean all
USER 1001
WORKDIR /opt/app-root/src
COPY --from=build --chown=1001:0 /opt/app-root/src/dist ./dist
COPY --from=build --chown=1001:0 /opt/app-root/src/node_modules ./node_modules
COPY --from=build --chown=1001:0 /opt/app-root/src/package.json ./package.json
ENV NODE_ENV=production PORT=8080 TZ=America/Lima
EXPOSE 8080
STOPSIGNAL SIGTERM
CMD ["node", "dist/server.js"]
